#!/usr/bin/env node
import * as esbuild from "esbuild"
import * as fs from "node:fs"
import * as path from "node:path"
import { fileURLToPath } from "node:url"

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const ROOT = path.resolve(__dirname, "..")
const ENTRY = path.join(ROOT, "src", "ide", "index.tsx")
const OUTPUT_TS = path.join(ROOT, "src", "ide", "built.ts")

const result = await esbuild.build({
  entryPoints: [ENTRY],
  bundle: true,
  minify: true,
  write: false,
  format: "iife",
  target: "es2020",
  jsx: "automatic",
  jsxImportSource: "preact",
  alias: {
    "preact/jsx-runtime": path.resolve(ROOT, "node_modules/preact/jsx-runtime/dist/jsxRuntime.module.js"),
    "preact/hooks": path.resolve(ROOT, "node_modules/preact/hooks/dist/hooks.module.js"),
    preact: path.resolve(ROOT, "node_modules/preact/dist/preact.module.js"),
  },
  define: {
    "process.env.NODE_ENV": '"production"',
  },
})

const js = result.outputFiles[0].text
const gz = Buffer.byteLength(js, "utf-8")

const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>pond IDE</title>
<script src="https://cdn.tailwindcss.com"></script>
<script>
  tailwind.config = { darkMode: 'class', theme: { extend: {} } }
</script>
<style>
  html, body { background: #000; color: #e4e4e7; height: 100%; margin: 0; }
  * { box-sizing: border-box; }
</style>
</head>
<body>
<div id="root" class="h-screen"></div>
<script>__POND_IDE__BOOTSTRAP__</script>
<script>
${js}
</script>
</body>
</html>`

const ts = `// Generated by scripts/build-ide.mjs. Do not edit by hand.
// Bundle size (raw): ${(gz / 1024).toFixed(1)} KB
export const ideHtml: string = ${JSON.stringify(html)}
`
fs.writeFileSync(OUTPUT_TS, ts)
console.log(`[build-ide] wrote ${OUTPUT_TS} (${(gz / 1024).toFixed(1)} KB raw JS)`)
