#!/usr/bin/env node
// Builds the IDE + dashboard frontends into committed generated modules
// (src/ide/built.ts, src/dashboard/built.ts, src/ide/tailwind.css):
//
//  - JS bundles are emitted as standalone versioned assets (ide-<hash>.js)
//    so the host can serve them with immutable caching instead of re-sending
//    ~600 KB inline on every page load.
//  - Tailwind is COMPILED to a static stylesheet at build time (no
//    cdn.tailwindcss.com — the CDN script was a third-party script with full
//    page privileges and no integrity attribute; it also left every page
//    unstyled when offline).
//  - Every inline script carries a `__POND_NONCE__` placeholder that the host
//    replaces with a per-request nonce, so the pages can run a strict CSP
//    (script-src 'nonce-…', no unsafe-inline).
import * as esbuild from "esbuild"
import * as fs from "node:fs"
import * as path from "node:path"
import { createHash } from "node:crypto"
import { fileURLToPath } from "node:url"
import { spawnSync } from "node:child_process"

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const ROOT = path.resolve(__dirname, "..")

const aliasConfig = {
  "preact/jsx-runtime": path.resolve(ROOT, "node_modules/preact/jsx-runtime/dist/jsxRuntime.module.js"),
  "preact/hooks": path.resolve(ROOT, "node_modules/preact/hooks/dist/hooks.module.js"),
  preact: path.resolve(ROOT, "node_modules/preact/dist/preact.module.js"),
}

async function bundle(entry) {
  const result = await esbuild.build({
    entryPoints: [entry],
    bundle: true,
    minify: true,
    write: false,
    format: "iife",
    target: "es2020",
    jsx: "automatic",
    jsxImportSource: "preact",
    alias: aliasConfig,
    define: { "process.env.NODE_ENV": '"production"' },
  })
  return result.outputFiles[0].text
}

function assetHash(js) {
  return createHash("sha256").update(js).digest("hex").slice(0, 16)
}

// Compile Tailwind v4 to a static stylesheet. Auto-detection scans the repo
// (respecting .gitignore, so node_modules is excluded); the IDE, dashboard
// and template sources are the only class sources that matter.
function compileTailwind() {
  const input = path.join(ROOT, "src", "ide", "tailwind-input.css")
  const output = path.join(ROOT, "src", "ide", "tailwind.css")
  const cli = path.join(ROOT, "node_modules", "@tailwindcss", "cli", "dist", "index.mjs")
  const r = spawnSync(process.execPath, [cli, "-i", input, "-o", output, "--minify"], {
    cwd: ROOT,
    encoding: "utf-8",
  })
  if (r.status !== 0) {
    console.error(`[build-ide] tailwind compile failed:\n${r.stderr || r.stdout}`)
    process.exit(1)
  }
  const css = fs.readFileSync(output, "utf-8")
  // The compiled sheet replaces the CDN's runtime compilation; keep the
  // minimal safety-net styles that used to live in a separate <style> block.
  return css
}

function pageHtml({ title, assetPath, bootstrapPlaceholder, tailwindCss, js }) {
  // `</script>` inside the bundle would truncate the page; the bundle is
  // served as an external asset, so the only inline scripts are the bootstrap
  // (server-generated JSON, `<`-escaped by the host) and the nonce-tagged
  // script tags themselves.
  const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>${title}</title>
<style>
${tailwindCss}
</style>
</head>
<body>
<div id="root" class="h-screen"></div>
<script nonce="__POND_NONCE__">${bootstrapPlaceholder}</script>
<script nonce="__POND_NONCE__" src="${assetPath}"></script>
</body>
</html>`
  if (!html.includes(bootstrapPlaceholder)) {
    throw new Error(`[build-ide] bootstrap placeholder missing from ${title} page`)
  }
  return html
}

const ideJs = await bundle(path.join(ROOT, "src", "ide", "index.tsx"))
const dashJs = await bundle(path.join(ROOT, "src", "dashboard", "index.tsx"))
const tailwindCss = compileTailwind()

const ideHash = assetHash(ideJs)
const dashHash = assetHash(dashJs)
const ideHtml = pageHtml({
  title: "pond IDE",
  assetPath: `/assets/ide-${ideHash}.js`,
  bootstrapPlaceholder: "__POND_IDE__BOOTSTRAP__",
  tailwindCss,
  js: ideJs,
})
const dashHtml = pageHtml({
  title: "pond Dashboard",
  assetPath: `/assets/dashboard-${dashHash}.js`,
  bootstrapPlaceholder: "__POND_DASHBOARD__BOOTSTRAP__",
  tailwindCss,
  js: dashJs,
})

function builtModule(exportLines, extraComment) {
  return `// Generated by scripts/build-ide.mjs. Do not edit by hand.
// ${extraComment}
${exportLines.join("\n")}
`
}

const ideTs = builtModule(
  [
    `export const ideHtml: string = ${JSON.stringify(ideHtml)}`,
    `export const ideJs: string = ${JSON.stringify(ideJs)}`,
    `export const ideHash: string = ${JSON.stringify(ideHash)}`,
  ],
  `IDE bundle ${(Buffer.byteLength(ideJs, "utf-8") / 1024).toFixed(1)} KB raw; served as /assets/ide-${ideHash}.js`,
)
fs.writeFileSync(path.join(ROOT, "src", "ide", "built.ts"), ideTs)
console.log(`[build-ide] wrote src/ide/built.ts (${(Buffer.byteLength(ideJs, "utf-8") / 1024).toFixed(1)} KB raw JS)`)

const dashTs = builtModule(
  [
    `export const dashboardHtml: string = ${JSON.stringify(dashHtml)}`,
    `export const dashboardJs: string = ${JSON.stringify(dashJs)}`,
    `export const dashboardHash: string = ${JSON.stringify(dashHash)}`,
  ],
  `Dashboard bundle ${(Buffer.byteLength(dashJs, "utf-8") / 1024).toFixed(1)} KB raw; served as /assets/dashboard-${dashHash}.js`,
)
fs.mkdirSync(path.join(ROOT, "src", "dashboard"), { recursive: true })
fs.writeFileSync(path.join(ROOT, "src", "dashboard", "built.ts"), dashTs)
console.log(
  `[build-ide] wrote src/dashboard/built.ts (${(Buffer.byteLength(dashJs, "utf-8") / 1024).toFixed(1)} KB raw JS)`,
)
