#!/usr/bin/env node
import * as esbuild from "esbuild"
import * as fs from "node:fs"
import * as path from "node:path"
import { fileURLToPath } from "node:url"

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const ROOT = path.resolve(__dirname, "..")

const aliasConfig = {
  "preact/jsx-runtime": path.resolve(ROOT, "node_modules/preact/jsx-runtime/dist/jsxRuntime.module.js"),
  "preact/hooks": path.resolve(ROOT, "node_modules/preact/hooks/dist/hooks.module.js"),
  preact: path.resolve(ROOT, "node_modules/preact/dist/preact.module.js"),
}

async function bundle(entry) {
  const result = await esbuild.build({
    entryPoints: [entry],
    bundle: true,
    minify: true,
    write: false,
    format: "iife",
    target: "es2020",
    jsx: "automatic",
    jsxImportSource: "preact",
    alias: aliasConfig,
    define: { "process.env.NODE_ENV": '"production"' },
  })
  return result.outputFiles[0].text
}

function pageHtml({ title, bootstrapPlaceholder, js }) {
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>${title}</title>
<script src="https://cdn.tailwindcss.com"></script>
<script>
  tailwind.config = { darkMode: 'class', theme: { extend: {} } }
</script>
<style>
  html, body { background: #000; color: #e4e4e7; height: 100%; margin: 0; }
  * { box-sizing: border-box; }
</style>
</head>
<body>
<div id="root" class="h-screen"></div>
<script>${bootstrapPlaceholder}</script>
<script>
${js}
</script>
</body>
</html>`
}

const ideJs = await bundle(path.join(ROOT, "src", "ide", "index.tsx"))
const ideHtml = pageHtml({ title: "pond IDE", bootstrapPlaceholder: "__POND_IDE__BOOTSTRAP__", js: ideJs })
const ideTs = `// Generated by scripts/build-ide.mjs. Do not edit by hand.
// Bundle size (raw): ${(Buffer.byteLength(ideJs, "utf-8") / 1024).toFixed(1)} KB
export const ideHtml: string = ${JSON.stringify(ideHtml)}
`
fs.writeFileSync(path.join(ROOT, "src", "ide", "built.ts"), ideTs)
console.log(`[build-ide] wrote src/ide/built.ts (${(Buffer.byteLength(ideJs, "utf-8") / 1024).toFixed(1)} KB raw JS)`)

const dashJs = await bundle(path.join(ROOT, "src", "dashboard", "index.tsx"))
const dashHtml = pageHtml({
  title: "pond Dashboard",
  bootstrapPlaceholder: "__POND_DASHBOARD__BOOTSTRAP__",
  js: dashJs,
})
const dashTs = `// Generated by scripts/build-ide.mjs. Do not edit by hand.
// Bundle size (raw): ${(Buffer.byteLength(dashJs, "utf-8") / 1024).toFixed(1)} KB
export const dashboardHtml: string = ${JSON.stringify(dashHtml)}
`
fs.mkdirSync(path.join(ROOT, "src", "dashboard"), { recursive: true })
fs.writeFileSync(path.join(ROOT, "src", "dashboard", "built.ts"), dashTs)
console.log(
  `[build-ide] wrote src/dashboard/built.ts (${(Buffer.byteLength(dashJs, "utf-8") / 1024).toFixed(1)} KB raw JS)`,
)
